### PR TITLE
Added Hosted Site

### PR DESCRIPTION
**Pull request by michaeljamie**

### CODE REVIEW

**Comment by voldemortensen** [comment]
Thanks!

**Comment by michaeljamie** [comment]
Sure thing!

**Comment by rdela** [comment]
@michaeljamie is there CI set up on this? Should we set that up or switch over to Netlify?

**Comment by michaeljamie** [comment]
@rdela just messaged @voldemortensen with the login details.  My apologies for not seeing this earlier!

**Comment by voldemortensen** [comment]
@rdela I've just updated the example site. I'm good with switching to Netlify to take advantage of auto-deployments. When I created an org I overlooked the fact that GitHub Actions wouldn't be available.

**Comment by voldemortensen** [comment]
@rdela this will deploy on netlify now. I also setup [example.scantjs.com](https://example.scantjs.com)

**Comment by rdela** [comment]
Thank you both!

**Pull request merged**
